export { default as EditorArea } from './editor-area/EditorArea'
export { default as FileStructure } from './file-structure/FileStructure'
export { default as TerminalPane } from './terminal-pane/TerminalPane'
export { default as WorkspaceMenu } from './workspace-menu/WorkspaceMenu'
export { default as RemoteRepoModal } from './remote-repo/RemoteRepoModal'
